### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by jinxdash** [jinxdash/prettier-plugin-rust#3]
# Roadmap 1.0.0

The project is missing a few non-essential features necessary for a "full" release:

- ## Crate
  [This project](https://github.com/jinxdash/prettier-plugin-rust/tree/master/crate) reserved the crate [`prettier`](https://crates.io/crates/prettier) for future use.
  - [ ] Provide a prettier cli
  - [ ] Rust binding for `prettier.format`

- ## Plugin
  - [ ] [major] Playground website to reproduce issues online
  - [ ] [major] Formatting for `macro_rules!` right-hand side "transformed" part
    - [ ] [`jinx-rust`](https://github.com/jinxdash/jinx-rust): Add `rs.fromTransformed` method  that parses transformed blocks and handles special `$` nodes
  - [ ] Support complex formatting of macro invocations inside types and patterns.
    - [ ] [`jinx-rust`](https://github.com/jinxdash/jinx-rust): Add invocation context to `MacroInvocation` nodes (e.g. `node.ctx: "Pattern" | "Statement" | ...`)
    - [ ] [`jinx-rust`](https://github.com/jinxdash/jinx-rust): Add `rs.toType` and `rs.toPattern`
  - [ ] Custom formatting for macros `matches!`, `if_chains!` (others?)
  - [ ] Support `trailingComma: "es5" | "none" | "all"` (currently always `"es5"`)
  - [ ] Support embeds  

- ## Extension

  Hopefully the official extension [gets better plugin support](https://github.com/prettier/prettier-vscode/issues/2671). But if this project has to have an extension, it should be done properly.

  - [ ] Support "format selection"
  - [ ] Investigate and document a rustfmt config that is compatible with prettier's output
  - [ ] Take `.prettierignore` into account and add prompt when formatting fails because of it
  - [ ] Auto-open extension output on internal extension error
  - [ ] Write tests

- ## GitHub
  - [ ] Setup CI tests for pull requests
  - [ ] Investigate how to automatically publish each item (crate, package, extension)

<br>

---

I'll begin working on adding features once the plugin gets a userbase going, and the initial bugs and edge cases are dealt with.

_The thread is open for questions, requests, complaints~_

**Comment by BlueskyFR** [comment]
hey! Is this project still maintained? Just wondering if it is since it looks really promising!

**Comment by ghost** [comment]
Doesn't look like it
